/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * This is the OpenAPI definition of the CSAF 2.0 Distribution API v1 designed to be implemented in (trusted) providers
 *
 * API version: 0.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package router

type DeviceList []Device

type Device struct {
	Cpe           string `json:"cpe,omitempty"`
	Hashes        string `json:"hashes,omitempty"`
	ModelNumbers  string `json:"model_numbers,omitempty"`
	Purl          string `json:"purl,omitempty"`
	SbomUrls      string `json:"sbom_urls,omitempty"`
	SerialNumbers string `json:"serial_numbers,omitempty"`
	Skus          string `json:"skus,omitempty"`
	XGenericUris  string `json:"x_generic_uris,omitempty"`
}
