/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * This is the OpenAPI definition of the CSAF 2.0 Distribution API v1.
 *
 * API version: 0.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package router

import "github.com/csaf-poc/csaf_distribution/csaf"

type ModelError struct {
	Errcode string `json:"errcode"`          // Parsable, enumerated error code
	Errmsg  string `json:"errmsg,omitempty"` // Stateful error message
}

type GenericResponse struct {
	Error *ModelError `json:"error"`
}

type CSAFDocumentResponseDocuments struct {
	Content   *csaf.CsafJson     `json:"content"`
	Signature *string            `json:"signature,omitempty"`
	Hashes    *map[string]string `json:"hashes,omitempty"`
}

type CSAFDocumentResponse struct {
	GenericResponse `json:",inline"`
	DocumentsFound  int                             `json:"documents_found"`
	Documents       []CSAFDocumentResponseDocuments `json:"documents"`
}
