/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * This is the OpenAPI definition of the CSAF 2.0 Distribution API v1 designed to be implemented in (trusted) providers
 *
 * API version: 0.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package router

type AdvancedMatchingMatches struct {
	Path           string       `json:"path"`
	Type           string       `json:"type,omitempty"`
	Value          *interface{} `json:"value"`
	Matching       string       `json:"matching,omitempty"`
	IncludeMissing bool         `json:"include_missing,omitempty"`
}

type AdvancedMatching struct {
	MatchingDefault string                    `json:"matching_default,omitempty"`
	Operator        string                    `json:"operator,omitempty"`
	Matches         []AdvancedMatchingMatches `json:"matches"`
}
