/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * This is the OpenAPI definition of the CSAF 2.0 Distribution API v1 designed to be implemented in (trusted) providers
 *
 * API version: 0.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package router

type ModelError struct {
	Errcode string `json:"errcode"`          // Parsable, enumerated error code
	Errmsg  string `json:"errmsg,omitempty"` // Stateful error message
}
