/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * This is the OpenAPI definition of the CSAF 2.0 Distribution API v1 designed to be implemented in (trusted) providers
 *
 * API version: 0.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package router

type MetadataResponse struct {
	Error            *ModelError  `json:"error"`
	ProviderMetadata *interface{} `json:"provider_metadata,omitempty"` // See https://docs.oasis-open.org/csaf/csaf/v2.0/provider_json_schema.json
	Aggregator       *interface{} `json:"aggregator,omitempty"`        // See https://docs.oasis-open.org/csaf/csaf/v2.0/aggregator_json_schema.json
}
