/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * This is the OpenAPI definition of the CSAF 2.0 Distribution API v1.
 *
 * API version: 0.1.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package router

import "github.com/csaf-poc/csaf_distribution/csaf"

type CsafDocumentResponse struct {
	Error          *ModelError     `json:"error"`
	DocumentsFound int             `json:"documents_found"`
	Documents      []csaf.CsafJson `json:"documents"`
}
