/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * Base file
 *
 * API version: 0.1.1
 * Contact: pending@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"fmt"
	"log"
	"net/http"

	sw "github.com/csaf-poc/csaf_distribution/cmd/csaf_api/go"
)

func main() {
	log.Printf("Server started")

	c, err := loadConfig("../../docs/examples/api.toml")
	if err != nil {
		panic(err)
	}
	fmt.Println(c)

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(c.BindAddress, router))
}
