/*
 * Common Security Advisory Framework (CSAF) 2.0 Distribution API
 *
 * Base file
 *
 * API version: 0.1.1
 * Contact: pending@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/jessevdk/go-flags"

	sw "github.com/csaf-poc/csaf_distribution/cmd/csaf_api/go"
)

type options struct {
	Config string `short:"c" long:"config" description:"File name of the configuration file" value-name:"CFG-FILE" default:"api.toml"`
}

func main() {

	opts := new(options)
	_, err := flags.Parse(opts)
	if err != nil {
		log.Fatalf("error: %v\n", err)
	}

	log.Println("Loading config")
	c, err := loadConfig(opts.Config)
	if err != nil {
		log.Fatalf("error: %v\n", err)
	}

	log.Println("Loading API server routes")
	router := sw.NewRouter()

	log.Println("Starting API server")
	log.Fatal(http.ListenAndServe(c.BindAddress, router))
}
